### ISSUE TITLE
How can I solve Imagefolder dataset problem? 

### ISSUE THREAD

**Issue by donaldaq** [bomri/code-for-posts#1]
Thank you for your posts
I have a problem about imagefolder in pytorch? 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-55-dfa25d130bea> in <module>
     17                                                   sampler=BalancedBatchSchedulerSampler(dataset=image_datasets['train'],batch_size=16),
     18                                              shuffle=False, num_workers=4)
---> 19                   for x in ['train', 'val', 'test']}    
     20 
     21 dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'val', 'test']}

<ipython-input-55-dfa25d130bea> in <dictcomp>(.0)
     17                                                   sampler=BalancedBatchSchedulerSampler(dataset=image_datasets['train'],batch_size=16),
     18                                              shuffle=False, num_workers=4)
---> 19                   for x in ['train', 'val', 'test']}    
     20 
     21 dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'val', 'test']}

~/ml/pytorch-image-classification/imbalancedbatch/balanced_sampler.py in __init__(self, dataset, batch_size)
     22         self.dataset = dataset
     23         self.batch_size = batch_size
---> 24         self.number_of_datasets = len(dataset.datasets)
     25 
     26     def __len__(self):

AttributeError: 'ImageFolder' object has no attribute 'datasets'

**Comment by bomri** [comment]
Hey @donaldaq,

The `BalancedBatchSchedulerSampler` expect to get a dataset of type `ConcatDataset`, if you are working with only one dataset you should use `ImbalancedDatasetSampler`. If you do try to work with multiple datasets can you please share the code you are using.

**Comment by donaldaq** [comment]
> Hey @donaldaq,
> 
> The `BalancedBatchSchedulerSampler` expect to get a dataset of type `ConcatDataset`, if you are working with only one dataset you should use `ImbalancedDatasetSampler`. If you do try to work with multiple datasets can you please share the code you are using.

Thanks. I got it
